spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: "jdbc:postgresql://127.0.0.1:5432/musicme"
    username: harry
    password: postgres
    driverClassName: org.postgresql.Driver